spring:
  datasource:
    url: jdbc:mysql://47.106.78.139:3306/cw?useSSL=false&characterEncoding=utf-8
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  application:
    name: zhst-service-product

server:
  port: 8765

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
