spring:
  application:
    name: zhst-zuul

server:
  port: 8766

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
zuul:
  routes:
    api-a:
      path: /api/a/**
      serviceId: spring-cloud-admin-ribbon
    api-b:
      path: /api/b/**
      serviceId: spring-cloud-admin-feign

  add-proxy-headers: true #开启请求头代理