spring:
  application:
    name: zhst-service-redis
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 500
        min-idle: 0
    sentinel:
        master: mymaster
        nodes: 192.168.75.140:26379, 192.168.75.140:26380, 192.168.75.140:26381


server:
  port: 8789

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


